config/routes.rb
Rails.application.routes.draw do
  get 'landings/x'

  get 'landings/y'

  get 'landings/z'

  get 'pages/index'

  get 'pages/about'

  get 'pages/contact'

  root 'landings#z'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :xyz

  private
  def xyz
  	@array = [:nombre1, :nombre2, :nombre3, :nombre4, :nombre5, :nombre6, :nombre7, :nombre8, :nombre9, :nombre10]
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def x
  end

  def y
  end

  def z

  	
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/landings/x.html.erb
<h1>Landings#x</h1>
<p>Find me in app/views/landings/x.html.erb</p>

<%= @array.each {} %>

app/views/landings/y.html.erb
<h1>Landings#y</h1>
<p>Find me in app/views/landings/y.html.erb</p>

<%= @array.each {} %>

app/views/landings/z.html.erb
<h1>Landings#z</h1>
<p>Find me in app/views/landings/z.html.erb</p>


<%= @array.each {} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="nav-bar">

  <%= link_to "x", landings_x_path %>
  <%= link_to "y", landings_y_path %>
  <%= link_to "z", landings_z_path %>
  	
  </div>
    <%= yield %>
  </body>
</html>

<style>
.nav-bar{
	width: 100%;
	height: 50px;
	background-color: grey;

}
	
	
</style>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>